<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DspVoucher extends Model
{
    use HasFactory;

    protected $fillable = [
        'code',
        'generated_by_id',
        'used_by_id',
        'is_used',
		'used_at',
    ];

    /**
     * Relationship: Voucher generated by a user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by_id');
    }

    /**
     * Relationship: Voucher used by a user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function usedBy()
    {
        return $this->belongsTo(User::class, 'used_by_id');
    }

    /**
     * Scope: Filter used vouchers.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeUsed($query)
    {
        return $query->where('is_used', true);
    }

    /**
     * Scope: Filter unused vouchers.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeUnused($query)
    {
        return $query->where('is_used', false);
    }

}