@extends('admin.layouts.app')
@section('panel')
<style>
    @media (max-width: 767px) {
        table.style--two tbody tr {
            border: 2px dashed #0000005c;
            display: block;
            margin-bottom: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
            transition: box-shadow 0.3s ease-in-out;
        }
        table.style--two tbody tr:hover {
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.4);
            transition: box-shadow 0.3s ease-in-out;
        }
    }
    .voucher-code {
        font-family: monospace;
        letter-spacing: 2px;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body p-0">
                <div class="table-responsive--md  table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                            <tr>
                                <th>@lang('S No.')</th>
                                <th>@lang('Voucher Code')</th>
                                <th>@lang('Generated By')</th>
                                <th>@lang('Generated On')</th>
                                <th>@lang('Status')</th>
                                <th>@lang('Used By')</th>
                                <th>@lang('Used On')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($vouchers as $voucher)
                            <tr>
                                <td>{{ $vouchers->firstItem() + $loop->index }}</td>
                                
                                <td class="voucher-code">
                                    {{ chunk_split($voucher->code, 4, ' ') }}
                                </td>
                                
                                <td>
                                    <a href="{{ route('admin.users.detail', $voucher->generatedBy->id) }}">
                                        {{ $voucher->generatedBy->fullname }}<br>
                                        <small>{{ $voucher->generatedBy->username }}</small>
                                    </a>
                                </td>
                                
                                <td>
                                    {{ showDateTime($voucher->created_at) }}<br>
                                    {{ diffForHumans($voucher->created_at) }}
                                </td>
                                
                                <td>
                                    @if($voucher->is_used)
                                        <span class="badge bg-success">@lang('Used')</span>
                                    @else
                                        <span class="badge bg-warning">@lang('Unused')</span>
                                    @endif
                                </td>
                                
                                <td>
                                    @if($voucher->is_used && $voucher->usedBy)
                                        <a href="{{ route('admin.users.detail', $voucher->usedBy->id) }}">
                                            {{ $voucher->usedBy->fullname }}<br>
                                            <small>{{ $voucher->usedBy->username }}</small>
                                        </a>
                                    @else
                                        <span class="text-muted">Not used</span>
                                    @endif
                                </td>

                                <td>
                                    @if($voucher->used_at)
                                        {{ showDateTime($voucher->used_at) }}<br>
                                        {{ diffForHumans($voucher->used_at) }}
                                    @else
                                        <span class="text-muted">N/A</span>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-muted text-center" colspan="100%">@lang('No vouchers found')</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            @if ($vouchers->hasPages())
            <div class="card-footer py-4">
                {{ paginateLinks($vouchers) }}
            </div>
            @endif
        </div>
    </div>
</div>

 <div class="row gy-4 mt-2">
    <div class="col-xxl-3 col-sm-6">
        <x-widget value="{{ $totalVouchers }}" title="Total Vouchers" style="7"
            link="#" icon="las la-ticket-alt" bg="3" />
    </div><div class="col-xxl-3 col-sm-6">
        <x-widget value="{{ $usedVouchers }}" title="Used Vouchers" style="7"
            link="#" icon="las la-check-circle" bg="4" />
    </div></div>@endsection

@push('breadcrumb-plugins')
<div class="d-flex flex-wrap justify-content-end">
    <form action="" method="GET" class="form-inline">
        <div class="input-group justify-content-end">
            <input type="text" name="search" class="form-control bg--white" placeholder="@lang('Search by user')" value="{{ request()->search }}">
            <input type="date" name="date" class="form-control bg--white" value="{{ request()->date }}">
            <button class="btn btn--primary input-group-text" type="submit"><i class="fa fa-search"></i></button>
        </div>
    </form>
</div>
@endpush