<?php

namespace App\Http\Controllers;

use App\Constants\Status;
use App\Models\AdminNotification;
use App\Models\BonusWallets;
use App\Models\DspBonus;
use App\Models\DspFormulas;
use App\Models\DspVoucher;
use App\Models\Transaction;
use App\Models\User;
use App\Models\UserExtra;
use App\Models\WalletHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class VoucherController extends Controller
{
    /**
     * Display DSP Vouchers for the authenticated user.
     *
     * @return \Illuminate\View\View
     */
    public function viewDspVouchers()
    {
        // Fetch vouchers generated by the authenticated user
        $vouchers = DspVoucher::where('generated_by_id', auth()->id())
            ->orderBy('created_at', 'desc')
            ->paginate(10);

        // Total Vouchers Count
        $totalVouchers = $vouchers->total();

        // Used Vouchers Count
        $usedVouchers = DspVoucher::where('generated_by_id', auth()->id())
            ->where('is_used', true)
            ->count();

        // Latest Voucher Code
        $latestVoucher = DspVoucher::where('generated_by_id', auth()->id())
            ->latest()
            ->first();

        $pageTitle = 'DSP Vouchers';
        $emptyMessage = 'No DSP Vouchers found.';

        return view('templates.basic.user.dsp_vouchers', compact('vouchers', 'totalVouchers', 'usedVouchers', 'latestVoucher', 'pageTitle', 'emptyMessage'));
    }

    /**
     * Generate DSP Voucher Codes.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function generateVoucherCodes(Request $request)
    {
        $user = auth()->user();

        if ($user->pv < 100) {
            return response()->json([
                'success' => false,
                'message' => 'You do not have enough PV to generate a voucher.',
            ]);
        }

        $user->pv -= 100;
        $user->save();

        $code = strtoupper(Str::random(20));

        DspVoucher::create([
            'code' => $code,
            'generated_by_id' => $user->id,
            'is_used' => false,
        ]); //

        return response()->json([
            'success' => true,
            'code' => $code,
            'remaining_pv' => $user->pv,
        ]);
    }

    /**
     * Redeem a voucher for self-activation or to create a new DSP user.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function redeemVoucher(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'code' => 'required|string|exists:dsp_vouchers,code',
            'redeem_type' => 'required|in:self_activation,create_dsp',
            'placement_username' => 'required_if:redeem_type,create_dsp|string',
            'position' => 'required_if:redeem_type,create_dsp|in:1,2',
        ],[
            'placement_username.required_if' => 'The placement username field is required.',
            'position.required_if' => 'The position field is required.'
        ]); //

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }
        
        $user = auth()->user();
        $voucher = DspVoucher::where('code', $request->code)->first();

        if ($voucher->is_used) {
            return response()->json(['success' => false, 'message' => 'This voucher has already been used.']);
        }
        
        DB::beginTransaction();
        try {
            $voucher->is_used = true;
            $voucher->used_by_id = $user->id;
            $voucher->used_at = now();
            $voucher->save();

            $dspUsername = null;
            $placementUser = null; 

            if ($request->redeem_type == 'self_activation') {
                if ($user->plan_id != 0) {
                     DB::rollBack();
                     return response()->json(['success' => false, 'message' => 'Your account is already activated.']);
                }
                $user->plan_id = 1;
                updatePaidCount($user->id);

            } elseif ($request->redeem_type == 'create_dsp') {
                if ($user->plan_id == 0) {
                     DB::rollBack();
                     return response()->json(['success' => false, 'message' => 'You must have an active plan to place a DSP.']);
                }

                $placementUser = User::where('username', $request->placement_username)->first();
                if (!$placementUser) {
                    DB::rollBack();
                    return response()->json(['success' => false, 'message' => 'Placement user not found.']);
                }
                
                if (!treeAuth($placementUser->id, auth()->id())) {
                    DB::rollBack();
                    return response()->json(['success' => false, 'message' => 'You can only place new users within your own downline tree.']);
                }

                $pos = getPosition($placementUser->id, $request->position);

                $latestDspUser = User::where('dsp_username', 'LIKE', 'dsp%')
                                     ->orderByRaw('CAST(SUBSTRING(dsp_username, 4) AS UNSIGNED) DESC')
                                     ->first();

                $nextDspNumber = 1; 
                if ($latestDspUser) {
                    $lastDspNumber = (int) substr($latestDspUser->dsp_username, 3);
                    $nextDspNumber = $lastDspNumber + 1;
                }
                
                $dspUsername = 'dsp' . $nextDspNumber;
                
                $dspUser = new User();
                $dspUser->firstname = $user->firstname . ' ' . $user->lastname;
                $dspUser->lastname = 'DSP';
                $dspUser->email = strtolower($dspUsername);
                $dspUser->password = Hash::make(Str::random(12));
                $dspUser->username = $dspUsername;
                $dspUser->dsp_username = $dspUsername;
                $dspUser->ref_by = $placementUser->id;
                $dspUser->pos_id = $pos['pos_id'];
                $dspUser->position = $pos['position'];
                $dspUser->dsp_ref_by = $user->username;
                $dspUser->plan_id = 1;
                $dspUser->kv = gs('kv') ? Status::NO : Status::YES;
                $dspUser->ev = Status::NO;
                $dspUser->sv = Status::NO;
                $dspUser->ts = Status::DISABLE;
                $dspUser->tv = Status::ENABLE;
                $dspUser->save();
                
                $userExtras = new UserExtra();
                $userExtras->user_id = $dspUser->id;
                $userExtras->save();
                
                updateFreeCount($dspUser->id);
                updatePaidCount($dspUser->id);

                $adminNotification = new AdminNotification();
                $adminNotification->user_id = $dspUser->id;
                $adminNotification->title = 'New DSP created via voucher by ' . $user->username;
                $adminNotification->click_url = urlPath('admin.users.detail', $dspUser->id);
                $adminNotification->save();
            }

            $dspBonusInfo = DspBonus::where('bonus_type', 'dsp_bonus')->first();
            $dspRefBonusInfo = DspBonus::where('bonus_type', 'dsp_ref_bonus')->first();

            $dspBonusAmount = $dspBonusInfo ? $dspBonusInfo->bonus_amount : 0;
            $dspRefBonusAmount = $dspRefBonusInfo ? $dspRefBonusInfo->bonus_amount : 0;

            $distributedBonuses = [];
            
            if ($dspBonusAmount > 0) {
                $userBalanceBonus = $dspBonusAmount * 0.76;
                $userEpinCreditBonus = $dspBonusAmount * 0.24;

                $user->balance += $userBalanceBonus;
                $user->epin_credit += $userEpinCreditBonus;

                $transaction = new Transaction();
                $transaction->user_id = $user->id;
                $transaction->amount = $dspBonusAmount;
                $transaction->post_balance = $user->balance;
                $transaction->charge = 0;
                $transaction->trx_type = '+';
                $transaction->trx = getTrx();
                
                $dspBonusDetails = 'Received DSP Bonus for your DSP account activation.';
                if ($request->redeem_type == 'create_dsp') {
                    $dspBonusDetails = 'Received DSP Bonus for creating new DSP: ' . $dspUsername;
                }
                $transaction->details = $dspBonusDetails;

                $transaction->remark = 'dsp_bonus';
                $transaction->save();

                $distributedBonuses['dsp_bonus'] = $dspBonusAmount;
            }

            $referralUser = null;
            if ($dspRefBonusAmount > 0) {
                if ($request->redeem_type == 'create_dsp') {
                    $referralUser = $user;
                } elseif ($request->redeem_type == 'self_activation' && $user->ref_by) {
                    $referralUser = User::find($user->ref_by);
                }

                if ($referralUser) {
                    $refBalanceBonus = $dspRefBonusAmount * 0.76;
                    $refEpinCreditBonus = $dspRefBonusAmount * 0.24;

                    $referralUser->balance += $refBalanceBonus;
                    $referralUser->epin_credit += $refEpinCreditBonus;
                    $referralUser->save();

                    $refTransaction = new Transaction();
                    $refTransaction->user_id = $referralUser->id;
                    $refTransaction->amount = $dspRefBonusAmount;
                    $refTransaction->post_balance = $referralUser->balance;
                    $refTransaction->charge = 0;
                    $refTransaction->trx_type = '+';
                    $refTransaction->trx = getTrx();

                    $dspRefBonusDetails = 'Received DSP Referral Bonus from ' . $user->username . '\'s activation.';
                    if ($request->redeem_type == 'create_dsp') {
                        $dspRefBonusDetails = 'Received DSP Referral Bonus for creating new DSP: ' . $dspUsername;
                    }
                    $refTransaction->details = $dspRefBonusDetails;

                    $refTransaction->remark = 'dsp_ref_bonus';
                    $refTransaction->save();

                    $distributedBonuses['dsp_ref_bonus'] = $dspRefBonusAmount;
                }
            }

            $user->save();

            $formulas = DspFormulas::first();
            $remainingBonuses = [];

            if ($formulas) {
                $bonusWallet = BonusWallets::find(1);
                if ($bonusWallet) {
                    $bonusWallet->dsp_balance += ($formulas->dsp_formula - $dspBonusAmount);
                    $bonusWallet->direct_reference_balance += ($formulas->direct_reference_formula - $dspRefBonusAmount);
                    $bonusWallet->pair_balance += $formulas->pair_formula;
                    $bonusWallet->reward_balance += $formulas->reward_formula;
                    $bonusWallet->weekly_promo_balance += $formulas->weekly_promo_formula;
                    $bonusWallet->budget_promo_balance += $formulas->budget_promo_formula;
                    $bonusWallet->event_balance += $formulas->event_formula;
                    $bonusWallet->visit_outside_balance += $formulas->visit_outside_formula;
                    $bonusWallet->shipping_balance += $formulas->shipping_formula;
                    $bonusWallet->office_balance += $formulas->office_formula;
                    $bonusWallet->it_balance += $formulas->it_formula;
                    $bonusWallet->pintapay_balance += $formulas->pintapay_formula;
                    $bonusWallet->products_balance += $formulas->products_formula;
                    $bonusWallet->bbs_balance += $formulas->bbs_formula;
                    $bonusWallet->student_balance += $formulas->student_formula;
                    $bonusWallet->extra_balance += $formulas->extra_formula;
                    $bonusWallet->company_balance += $formulas->company_formula;
                    
                    $bonusWallet->save();

                    $allFormulas = $formulas->toArray();
                    unset($allFormulas['id'], $allFormulas['name'], $allFormulas['created_at'], $allFormulas['updated_at'], $allFormulas['dsp_price']);
                    
                    unset($allFormulas['dsp_formula']);
                    unset($allFormulas['direct_reference_formula']);

                    $remainingBonuses = $allFormulas;

                } else {
                    DB::rollBack();
                    Log::critical('Global bonus wallet with ID 1 not found.');
                    return response()->json(['success' => false, 'message' => 'System configuration error. Please contact support.']);
                }
            } else {
                 Log::warning('Dsp Formulas not found in the database.');
            }

            WalletHistory::create([
                'user_id' => $user->id,
                'voucher_id' => $voucher->id,
                'distributed_bonuses' => $distributedBonuses,
                'remaining_bonuses' => $remainingBonuses,
            ]);

            $transaction = new Transaction();
            $transaction->user_id = $user->id;
            $transaction->amount = 0;
            $transaction->post_balance = $user->balance;
            $transaction->charge = 0;
            $transaction->trx_type = '+';
            $transaction->trx = getTrx(); 
            
            if ($request->redeem_type == 'self_activation') {
                $transaction->details = 'Redeemed voucher ' . $voucher->code . ' for DSP account activation.';
                $transaction->remark = 'self_activation_via_voucher';
            } else {
                $transaction->details = 'Redeemed voucher ' . $voucher->code . ' to create new DSP: ' . $dspUsername;
                $transaction->remark = 'create_dsp_via_voucher';
            }
            
            $transaction->save();

            DB::commit();
            return response()->json(['success' => true, 'message' => 'Voucher redeemed successfully! Your page will now reload.']);

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Voucher Redemption Error: ' . $e->getMessage());
            Log::error($e);
            return response()->json(['success' => false, 'message' => 'An unexpected error occurred. Please try again.']);
        }
    }

    /**
     * Check if a placement username exists and is valid.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function checkPlacementUser(Request $request)
    {
        $request->validate(['username' => 'required|string']);
        $placementUser = User::where('username', $request->username)->first();

        if ($placementUser) {
            if (!treeAuth($placementUser->id, auth()->id())) {
                 return response()->json(['success' => false, 'msg' => 'You can only place new users within your own downline tree.']);
            }

            return response()->json([
                'success' => true, 'msg' => "User {$placementUser->firstname} {$placementUser->lastname} found.",
                'user' => ['id' => $placementUser->id, 'firstname' => $placementUser->firstname, 'lastname' => $placementUser->lastname]
            ]);
        } else {
            return response()->json(['success' => false, 'msg' => 'Placement username not found.']);
        }
    }

    /**
     * Get the final placement details for the tree.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getPlacementPosition(Request $request)
    {
        $request->validate([
            'referrer_id' => 'required|integer|exists:users,id',
            'position' => 'required|in:1,2'
        ]);

        $user = User::find($request->referrer_id);
        $pos = getPosition($user->id, $request->position);
        $join_under = User::find($pos['pos_id']);

        return response()->json([
            'success' => true,
            'join_under' => $join_under->username,
        ]);
    }
}